### PR TITLE
Removed duplicate type

### PR DESCRIPTION
**Pull request by jeperkins4**
This keeps popping up in our warnings.

### CODE REVIEW

**Comment by jamiemccarthy** [comment]
@martingordon My team is seeing this warning too. It seems #22 was clearly a mistake, it [added a duplicate type](https://github.com/martingordon/bronto-ruby/pull/22/files#diff-08c5778e7fc471868f0360d8a7c15978R36-R39), and this PR undoes that one.

Could we get this merged and a new version released please?

**Comment by martingordon** [comment]
@jeperkins4 Sorry for missing this!

@jamiemccarthy Just merged and updated to version 0.3.4.

**Comment by jamiemccarthy** [comment]
@martingordon Awesome, thank you! Do you mind doing a `gem push` to share 0.3.4 with rubygems? :)

**Comment by martingordon** [comment]
@jamiemccarthy Just pushed an updated version. Sorry for the delay again!

**Pull request merged**
